USE ROLE ACCOUNTADMIN;

-- 1. Buat Role khusus untuk Juri Hackathon
CREATE ROLE IF NOT EXISTS HACKATHON_JUDGE;

-- 2. Berikan akses ke Warehouse agar aplikasinya bisa berjalan
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE HACKATHON_JUDGE;

-- 3. Berikan akses ke Database dan Schema
GRANT USAGE ON DATABASE GEOTECH TO ROLE HACKATHON_JUDGE;
GRANT USAGE ON SCHEMA GEOTECH.CORE TO ROLE HACKATHON_JUDGE;

-- 4. Berikan akses BACA (Select) ke semua tabel data (wajib agar dashboard tidak kosong)
GRANT SELECT ON ALL TABLES IN SCHEMA GEOTECH.CORE TO ROLE HACKATHON_JUDGE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA GEOTECH.CORE TO ROLE HACKATHON_JUDGE;

-- 5. Berikan akses untuk membuka Aplikasi Streamlit
GRANT USAGE ON STREAMLIT GEOTECH.CORE.GEOTECH_APP TO ROLE HACKATHON_JUDGE;

-- 6. Buat Akun User untuk masing-masing email evaluator
CREATE USER IF NOT EXISTS HACK2SKILL_EVALUATOR_1
  PASSWORD = 'GeoTechJudge2026!'
  EMAIL = 'hack2skillevaluator@gmail.com'
  DEFAULT_ROLE = HACKATHON_JUDGE
  MUST_CHANGE_PASSWORD = FALSE;

CREATE USER IF NOT EXISTS HACK2SKILL_EVALUATOR_2
  PASSWORD = 'GeoTechJudge2026!'
  EMAIL = 'evaluator@hack2skill.com'
  DEFAULT_ROLE = HACKATHON_JUDGE
  MUST_CHANGE_PASSWORD = FALSE;

-- 7. Masukkan User ke dalam Role Juri
GRANT ROLE HACKATHON_JUDGE TO USER HACK2SKILL_EVALUATOR_1;
GRANT ROLE HACKATHON_JUDGE TO USER HACK2SKILL_EVALUATOR_2;
